config/routes.rb
Rails.application.routes.draw do
  resources :chats, only: :create
  root "welcome#index"
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def create
    # Interaction with LLM can be slow - execute in the background
    ChatJob.perform_later(params[:message], params[:chat_id])

    # In the meantime, clear out the form text area that user just typed
    # The turbo stream response here is being returned over regular http request/response, NOT websocket
    render turbo_stream: turbo_stream.replace("chat_form", partial: "welcome/form",
                                                           locals: { chat_id: params[:chat_id] })
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @chat_id = SecureRandom.hex(20)
    Rails.logger.info("🗞️ Generated chat id: #{@chat_id}")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_markdown_updater.html.erb
<script>
  document.getElementById('<%= response_id %>').dataset.markdownTextUpdatedValue = '<%= cur_time %>';
</script>

app/views/chats/_response.html.erb
<div class="response-container">
  <span class="font-semibold text-lg opacity-60 tracking-wide">You</span>
  <div id="<%= prompt_id %>"
      class='max-w-none border border-green-500 bg-green-100 p-4 rounded-xl mb-7'>
      <p><%= prompt %></p>
  </div>

  <span class="font-semibold text-lg opacity-60 tracking-wide">Model</span>
  <div id="response_wrapper"
    data-controller="clipboard"
    class="mb-7">
    <div id="<%= response_id %>"
        data-controller='markdown-text'
        data-markdown-text-updated-value=''
        data-clipboard-target="source"
        class='prose prose-lg max-w-none border border-blue-500 bg-blue-100 p-4 rounded-xl mb-2'>
    </div>
    <div id="response_controls" class="flex justify-end">
      <button
        data-clipboard-target="button"
        data-action="clipboard#copy"
        class="text-xs uppercase font-semibold tracking-wider border border-gray-400 py-2 px-3 rounded-lg hover:bg-gray-100 transition duration-200 ease-in-out">
        <span class="opacity-75">Copy</span>
      </button>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OllamaChat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.9.0/build/styles/github-dark.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="min-h-screen flex flex-col">
    <main class="container mx-auto mt-28 px-5 flex-1">
      <%= yield %>
    </main>
  </body>
</html>

app/views/welcome/_form.html.erb
<%= form_with url: chats_path, html: { id: "chat_form", class: "mt-3" } do |f| %>
  <%= f.hidden_field :chat_id, value: chat_id %>
  <div class="flex">
    <div class="w-11/12">
      <%= f.text_area :message, class: "resize-none border rounded-md w-full py-2 px-3 text-gray-700 placeholder-gray-400 focus:outline-none focus:border-blue-500", placeholder: "Your message", autofocus: true %>
    </div>
    <div class="w-1/12 ml-2">
      <%= f.submit "Send", class: "uppercase tracking-wider bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded w-full" %>
    </div>
  </div>
<% end %>

app/views/welcome/index.html.erb
<div class="w-full">
  <span class="bg-yellow-200 border-yellow-400 text-yellow-700 px-4 py-2 mb-4 rounded-full inline-block">
    Using model: <%= Rails.application.config.chat["chat_model"] %>
  </span>

  <%# Subscribe to welcome channel for real-time updates via ActionCable %>
  <%# Use chat_id so that each connected client will have a unique chat session %>
  <%= turbo_stream_from @chat_id, "welcome" %>

  <%# Here is where we will stream the responses from the llm %>
  <%# Eventually this should consist of a sequence of questions and answers %>
  <div id="messages"
    data-controller="scroll"
    data-scroll-delay-value="100"
    class="overflow-y-auto max-h-[80vh]"></div>

  <%# The user types in their prompt here %>
  <%= render "form", chat_id: @chat_id %>
</div>